import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Pressable, StyleSheet, Text, View } from "react-native";

import { Eyebrow } from "@/components/filon/filon-ui";
import { ScreenContainer } from "@/components/screen-container";
import { startOAuthLogin } from "@/constants/oauth";
import { useColors } from "@/hooks/use-colors";
import { useAuth } from "@/hooks/use-auth";
import { type FilonLocale, useLocale } from "@/lib/locale";
import { type AppearancePreference, useThemeContext } from "@/lib/theme-provider";

const Check = ({ size, color }: { size: number; color: string }) => <MaterialIcons name="check" size={size} color={color} />;

const copy = {
  fr: { caption: "Préférences locales et informations sur les données.", account: "Compte FILON", connect: "Connecter mon compte", connected: "Compte connecté", guest: "Connectez-vous pour synchroniser vos seuils sur cet appareil.", sync: "Vos seuils peuvent être synchronisés depuis l’onglet Suivis.", disconnect: "Déconnecter", appearance: "Apparence", system: "Système", light: "Clair", dark: "Sombre", trust: "Données du catalogue FILON", trustText: "Les offres sont indexées par FILON. Confirmez le prix et les conditions auprès du marchand avant l’achat." },
  nl: { caption: "Lokale voorkeuren en informatie over de gegevens.", account: "FILON-account", connect: "Mijn account verbinden", connected: "Account verbonden", guest: "Log in om je drempels op dit apparaat te synchroniseren.", sync: "Je drempels kunnen worden gesynchroniseerd via het tabblad Volgen.", disconnect: "Afmelden", appearance: "Weergave", system: "Systeem", light: "Licht", dark: "Donker", trust: "Gegevens uit de FILON-catalogus", trustText: "Aanbiedingen worden door FILON geïndexeerd. Bevestig prijs en voorwaarden bij de handelaar voordat je koopt." },
  en: { caption: "Local preferences and information about the data.", account: "FILON account", connect: "Connect my account", connected: "Account connected", guest: "Sign in to synchronize your thresholds on this device.", sync: "Your thresholds can be synchronized from the Watching tab.", disconnect: "Sign out", appearance: "Appearance", system: "System", light: "Light", dark: "Dark", trust: "Data in the FILON catalogue", trustText: "Offers are indexed by FILON. Confirm the price and conditions with the merchant before buying." },
};

export default function ProfileScreen() {
  const { locale, setLocale, t } = useLocale();
  const auth = useAuth();
  const colors = useColors();
  const { appearancePreference, setAppearancePreference } = useThemeContext();
  const styles = createStyles(colors);
  const text = copy[locale];
  const accountName = auth.user?.name ?? auth.user?.email ?? text.connected;
  const preferenceOptions: { value: AppearancePreference; label: string; icon: keyof typeof MaterialIcons.glyphMap }[] = [{ value: "system", label: text.system, icon: "brightness-auto" }, { value: "light", label: text.light, icon: "light-mode" }, { value: "dark", label: text.dark, icon: "dark-mode" }];

  return <ScreenContainer containerClassName="bg-background"><View style={styles.content}><Eyebrow>FILON</Eyebrow><Text style={styles.title}>{t.profile}</Text><Text style={styles.caption}>{text.caption}</Text><Text style={styles.section}>{text.appearance}</Text><View style={styles.appearancePanel}>{preferenceOptions.map(({ value, label, icon }) => <Pressable key={value} accessibilityRole="radio" accessibilityState={{ selected: appearancePreference === value }} accessibilityLabel={label} onPress={() => setAppearancePreference(value)} style={({ pressed }) => [styles.appearanceOption, appearancePreference === value && styles.appearanceSelected, pressed && styles.pressed]}><MaterialIcons name={icon} size={18} color={appearancePreference === value ? colors.background : colors.muted} /><Text style={[styles.appearanceText, appearancePreference === value && styles.appearanceTextSelected]}>{label}</Text></Pressable>)}</View><Text style={styles.section}>{text.account}</Text><View style={styles.panel}><View style={styles.infoRow}><View style={styles.icon}><MaterialIcons name={auth.isAuthenticated ? "cloud-done" : "person-outline"} size={20} color={auth.isAuthenticated ? colors.success : colors.primary} /></View><View style={styles.infoCopy}><Text style={styles.infoTitle}>{auth.isAuthenticated ? accountName : text.connect}</Text><Text style={styles.infoText}>{auth.isAuthenticated ? text.sync : text.guest}</Text></View><Pressable accessibilityRole="button" accessibilityLabel={auth.isAuthenticated ? text.disconnect : text.connect} onPress={() => { if (auth.isAuthenticated) void auth.logout(); else void startOAuthLogin(); }} style={({ pressed }) => [styles.accountAction, pressed && styles.pressed]}><Text style={styles.accountActionText}>{auth.isAuthenticated ? text.disconnect : text.connect}</Text></Pressable></View></View><Text style={styles.section}>{t.language}</Text><View style={styles.panel}><LocaleRow value="fr" label="Français" current={locale} onSelect={setLocale} styles={styles} colors={colors} /><LocaleRow value="nl" label="Nederlands" current={locale} onSelect={setLocale} styles={styles} colors={colors} /><LocaleRow value="en" label="English" current={locale} onSelect={setLocale} styles={styles} colors={colors} /></View><Text style={styles.section}>FILON</Text><View style={styles.panel}><View style={styles.infoRow}><View style={styles.icon}><MaterialIcons name="info-outline" size={20} color={colors.primary} /></View><View style={styles.infoCopy}><Text style={styles.infoTitle}>{text.trust}</Text><Text style={styles.infoText}>{text.trustText}</Text></View></View></View></View></ScreenContainer>;
}

function LocaleRow({ value, label, current, onSelect, styles, colors }: { value: FilonLocale; label: string; current: FilonLocale; onSelect: (next: FilonLocale) => void; styles: ReturnType<typeof createStyles>; colors: ReturnType<typeof useColors> }) { const selected = value === current; return <Pressable accessibilityRole="radio" accessibilityState={{ selected }} accessibilityLabel={label} onPress={() => onSelect(value)} style={({ pressed }) => [styles.localeRow, pressed && styles.pressed]}><Text style={[styles.localeText, selected && styles.localeSelected]}>{label}</Text><View style={[styles.radio, selected && styles.radioSelected]}>{selected && <Check size={14} color={colors.background} />}</View></Pressable>; }

function createStyles(colors: ReturnType<typeof useColors>) { return StyleSheet.create({ content: { flex: 1, padding: 20 }, title: { color: colors.foreground, fontSize: 34, fontWeight: "800", letterSpacing: -0.8, marginTop: 6 }, caption: { color: colors.muted, fontSize: 14, lineHeight: 20, marginTop: 8 }, section: { color: colors.primary, fontSize: 11, fontWeight: "800", letterSpacing: 1.25, textTransform: "uppercase", marginTop: 28, marginBottom: 10 }, panel: { overflow: "hidden", borderRadius: 18, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, appearancePanel: { flexDirection: "row", gap: 8 }, appearanceOption: { flex: 1, minHeight: 68, paddingHorizontal: 8, borderRadius: 17, alignItems: "center", justifyContent: "center", gap: 6, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, appearanceSelected: { backgroundColor: colors.primary, borderColor: colors.primary }, appearanceText: { color: colors.muted, fontSize: 12, fontWeight: "700" }, appearanceTextSelected: { color: colors.background }, localeRow: { minHeight: 54, paddingHorizontal: 16, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: colors.border }, localeText: { color: colors.muted, fontSize: 15, fontWeight: "600" }, localeSelected: { color: colors.foreground }, radio: { width: 22, height: 22, borderRadius: 11, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: colors.border }, radioSelected: { backgroundColor: colors.primary, borderColor: colors.primary }, infoRow: { minHeight: 82, padding: 14, flexDirection: "row", gap: 12, alignItems: "center" }, icon: { width: 38, height: 38, borderRadius: 12, backgroundColor: `${colors.success}1F`, alignItems: "center", justifyContent: "center" }, infoCopy: { flex: 1 }, infoTitle: { color: colors.foreground, fontSize: 14, fontWeight: "700" }, infoText: { color: colors.muted, fontSize: 12, lineHeight: 17, marginTop: 3 }, accountAction: { minHeight: 38, paddingHorizontal: 10, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: colors.primary }, accountActionText: { color: colors.background, fontSize: 10, fontWeight: "800", textAlign: "center" }, pressed: { opacity: 0.72 } }); }
