import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { Alert, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { TactileButton } from "@/components/filon/filon-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useFavoriteCollections } from "@/hooks/use-favorite-collections";
import { useFavorites } from "@/hooks/use-favorites";
import { useLocale } from "@/lib/locale";
import { useState } from "react";

const copy = { fr: { back: "Retour", title: "Collections privées", subtitle: "Organisez vos suivis sur cet appareil.", create: "Créer une collection", placeholder: "Ex. À comparer ce week-end", add: "Ajouter", empty: "Créez une collection pour classer ce suivi.", assign: "Ajouter à", assigned: "Dans cette collection", edit: "Renommer", save: "Enregistrer", renamed: "Collection renommée", delete: "Supprimer", deleteTitle: "Supprimer cette collection ?", deleteBody: "Les suivis restent dans FILON, mais cette collection sera supprimée partout après synchronisation.", cancel: "Annuler" }, nl: { back: "Terug", title: "Privécollecties", subtitle: "Organiseer je gevolgde items op dit apparaat.", create: "Een collectie maken", placeholder: "Bijv. Dit weekend vergelijken", add: "Toevoegen", empty: "Maak een collectie om dit gevolgde item te ordenen.", assign: "Toevoegen aan", assigned: "In deze collectie", edit: "Hernoemen", save: "Opslaan", renamed: "Collectie hernoemd", delete: "Verwijderen", deleteTitle: "Deze collectie verwijderen?", deleteBody: "Je gevolgde items blijven in FILON, maar deze collectie wordt na synchronisatie overal verwijderd.", cancel: "Annuleren" }, en: { back: "Back", title: "Private collections", subtitle: "Organize your saved items on this device.", create: "Create a collection", placeholder: "e.g. Compare this weekend", add: "Add", empty: "Create a collection to organize this saved item.", assign: "Add to", assigned: "In this collection", edit: "Rename", save: "Save", renamed: "Collection renamed", delete: "Delete", deleteTitle: "Delete this collection?", deleteBody: "Your saved items stay in FILON, but this collection will be removed everywhere after sync.", cancel: "Cancel" } };

export default function ManageCollectionScreen() {
  const { offerId } = useLocalSearchParams<{ offerId: string }>();
  const { locale } = useLocale(); const text = copy[locale]; const collections = useFavoriteCollections(); const favorites = useFavorites(); const [draft, setDraft] = useState(""); const [editingId, setEditingId] = useState<string | null>(null); const [renameDraft, setRenameDraft] = useState("");
  const numericOfferId = Number(offerId); const offer = favorites.items.find((item) => item.id === numericOfferId); const assigned = new Set(collections.forOffer(numericOfferId).map((item) => item.id));
  const create = async () => { if (!draft.trim()) return; await collections.create(draft); setDraft(""); };
  const confirmRemove = (collectionId: string) => Alert.alert(text.deleteTitle, text.deleteBody, [{ text: text.cancel, style: "cancel" }, { text: text.delete, style: "destructive", onPress: () => void collections.remove(collectionId) }]);
  const saveRename = async () => { if (!editingId || !renameDraft.trim()) return; await collections.rename(editingId, renameDraft); setEditingId(null); Alert.alert(text.renamed); };
  return <ScreenContainer className="" edges={["top", "left", "right", "bottom"]}><ScrollView contentContainerStyle={styles.content}><TactileButton accessibilityLabel={text.back} onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={20} color="#E4DED4" /><Text style={styles.backText}>{text.back}</Text></TactileButton><Text style={styles.title}>{text.title}</Text><Text style={styles.subtitle}>{offer ? `${text.assign} ${offer.name}` : text.subtitle}</Text><Text style={styles.createLabel}>{text.create}</Text><View style={styles.createRow}><TextInput value={draft} onChangeText={setDraft} placeholder={text.placeholder} placeholderTextColor="#817A72" style={styles.input} returnKeyType="done" onSubmitEditing={() => void create()} /><TactileButton accessibilityLabel={text.add} onPress={() => void create()} style={styles.add}><Text style={styles.addText}>{text.add}</Text></TactileButton></View>{collections.collections.length === 0 ? <Text style={styles.empty}>{text.empty}</Text> : <View style={styles.list}>{collections.collections.map((collection) => <View key={collection.id} style={styles.collectionRow}>{editingId === collection.id ? <View style={styles.renameRow}><TextInput value={renameDraft} onChangeText={setRenameDraft} autoFocus style={styles.input} returnKeyType="done" onSubmitEditing={() => void saveRename()} /><TactileButton accessibilityLabel={text.save} onPress={() => void saveRename()} style={styles.add}><Text style={styles.addText}>{text.save}</Text></TactileButton><TactileButton accessibilityLabel={text.cancel} onPress={() => setEditingId(null)} style={styles.edit}><MaterialIcons name="close" size={20} color="#E4DED4" /></TactileButton></View> : <><TactileButton accessibilityLabel={collection.name} onPress={() => numericOfferId > 0 && void collections.toggle(numericOfferId, collection.id)} style={[styles.collection, assigned.has(collection.id) && styles.collectionAssigned]}><Text style={[styles.collectionName, assigned.has(collection.id) && styles.collectionNameAssigned]}>{collection.name}</Text><MaterialIcons name={assigned.has(collection.id) ? "check-circle" : "add-circle-outline"} size={20} color={assigned.has(collection.id) ? "#0E0C0B" : "#C89544"} /></TactileButton><TactileButton accessibilityLabel={text.edit} onPress={() => { setEditingId(collection.id); setRenameDraft(collection.name); }} style={styles.edit}><MaterialIcons name="edit" size={20} color="#C89544" /></TactileButton><TactileButton accessibilityLabel={text.delete} onPress={() => confirmRemove(collection.id)} style={styles.delete}><MaterialIcons name="delete-outline" size={20} color="#E59480" /></TactileButton></>}</View>)}</View>}</ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 48 }, back: { alignSelf: "flex-start", minHeight: 44, paddingHorizontal: 9, borderRadius: 14, flexDirection: "row", gap: 8, marginBottom: 15 }, backText: { color: "#E4DED4", fontSize: 14, fontWeight: "700" }, title: { color: "#E4DED4", fontSize: 30, fontWeight: "800", letterSpacing: -0.6 }, subtitle: { color: "#9D958C", fontSize: 13, lineHeight: 19, marginTop: 8 }, createLabel: { color: "#E4DED4", fontSize: 14, fontWeight: "800", marginTop: 28, marginBottom: 9 }, createRow: { minHeight: 52, flexDirection: "row", gap: 8 }, input: { flex: 1, minHeight: 52, paddingHorizontal: 14, borderRadius: 16, color: "#E4DED4", backgroundColor: "#1A1714", borderWidth: 1, borderColor: "#40362B", fontSize: 13 }, add: { minHeight: 52, paddingHorizontal: 16, borderRadius: 16, backgroundColor: "#C89544" }, addText: { color: "#0E0C0B", fontSize: 13, fontWeight: "800" }, empty: { color: "#9D958C", fontSize: 13, lineHeight: 19, marginTop: 22 }, list: { gap: 9, marginTop: 22 }, collectionRow: { flexDirection: "row", gap: 8, flexWrap: "wrap" }, collection: { flex: 1, minHeight: 56, paddingHorizontal: 16, flexDirection: "row", justifyContent: "space-between", borderRadius: 17, backgroundColor: "#1A1714", borderWidth: 1, borderColor: "#40362B" }, renameRow: { width: "100%", flexDirection: "row", gap: 8 }, edit: { width: 50, minHeight: 56, borderRadius: 17, backgroundColor: "#1A1714", borderWidth: 1, borderColor: "#40362B" }, delete: { width: 54, minHeight: 56, borderRadius: 17, backgroundColor: "rgba(229,148,128,0.08)", borderWidth: 1, borderColor: "rgba(229,148,128,0.28)" }, collectionAssigned: { backgroundColor: "#C89544", borderColor: "#C89544" }, collectionName: { color: "#E4DED4", fontSize: 14, fontWeight: "800" }, collectionNameAssigned: { color: "#0E0C0B" } });
