import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Image } from "expo-image";
import { useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { ActivityIndicator, FlatList, Modal, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";

import { TactileButton } from "@/components/filon/filon-ui";
import { useFilonCatalogueFacets, useFilonCatalogueMerchants } from "@/hooks/use-filon-catalogue-filters";
import { useFilonOfferFeed } from "@/hooks/use-filon-offer-feed";
import { useColors } from "@/hooks/use-colors";
import { filterOffers } from "@/lib/offer-filters";
import { currentFilonStock, formatFilonPrice, isFilonOfferPriceCurrent, type FilonOffer, type FilonOfferSort } from "@/lib/filon-api";
import { useLocale } from "@/lib/locale";
import { localizedTaxonomyOption } from "@/lib/taxonomy-presentation";
import { useFilonEvidenceNow } from "@/hooks/use-filon-evidence-now";

const copy = {
  fr: { back: "Retour", all: "Tout", filter: "Filtrer", closeFilters: "Fermer les filtres", clear: "Réinitialiser", apply: "Afficher les offres", stock: "Uniquement en stock", available: "En stock", unavailable: "Indisponible", unknown: "À confirmer", priceUnknown: "Prix à confirmer", sort: "Trier", relevance: "Pertinence", name: "Nom", brand: "Marque", merchant: "Marchand", searchBrand: "Rechercher une marque", searchMerchant: "Rechercher un marchand", results: "offres", loadMore: "Charger plus", loading: "Chargement…", empty: "Aucune offre dans cette sélection.", error: "Le catalogue est momentanément indisponible.", retry: "Réessayer", image: "Image indisponible", at: "chez" },
  nl: { back: "Terug", all: "Alles", filter: "Filter", closeFilters: "Filters sluiten", clear: "Herstellen", apply: "Aanbiedingen tonen", stock: "Alleen op voorraad", available: "Op voorraad", unavailable: "Niet beschikbaar", unknown: "Te bevestigen", priceUnknown: "Prijs te bevestigen", sort: "Sorteren", relevance: "Relevantie", name: "Naam", brand: "Merk", merchant: "Handelaar", searchBrand: "Zoek een merk", searchMerchant: "Zoek een handelaar", results: "aanbiedingen", loadMore: "Meer laden", loading: "Laden…", empty: "Geen aanbieding in deze selectie.", error: "De catalogus is tijdelijk niet beschikbaar.", retry: "Opnieuw proberen", image: "Afbeelding niet beschikbaar", at: "bij" },
  en: { back: "Back", all: "All", filter: "Filter", closeFilters: "Close filters", clear: "Reset", apply: "Show offers", stock: "In stock only", available: "In stock", unavailable: "Unavailable", unknown: "To confirm", priceUnknown: "Price to confirm", sort: "Sort", relevance: "Relevance", name: "Name", brand: "Brand", merchant: "Merchant", searchBrand: "Find a brand", searchMerchant: "Find a merchant", results: "offers", loadMore: "Load more", loading: "Loading…", empty: "No offer in this selection.", error: "The catalogue is temporarily unavailable.", retry: "Try again", image: "Image unavailable", at: "at" },
};

type CatalogueStyles = ReturnType<typeof createStyles>;

export function NativeCatalogueHeader({ title, subtitle, onBack, right }: { title: string; subtitle?: string; onBack?: () => void; right?: React.ReactNode }) {
  const { locale } = useLocale();
  const colors = useColors();
  const styles = createStyles(colors);
  return <View style={styles.header}>{onBack ? <Pressable accessibilityRole="button" accessibilityLabel={copy[locale].back} onPress={onBack} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-back" size={22} color={colors.foreground} /></Pressable> : <View style={styles.logoMark}><Text style={styles.logoText}>F</Text></View>}<View style={styles.headerWords}><Text numberOfLines={1} style={styles.headerTitle}>{title}</Text>{subtitle ? <Text numberOfLines={1} style={styles.headerSubtitle}>{subtitle}</Text> : null}</View>{right ?? <View style={styles.rightSpacer} />}</View>;
}

export function NativeOfferResults({ title, category, subcategories, query }: { title: string; category?: string; subcategories?: { name: string; count: number; slug?: string }[]; query?: string }) {
  const router = useRouter();
  const { locale } = useLocale();
  const colors = useColors();
  const styles = createStyles(colors);
  const text = copy[locale];
  const [activeSubcategory, setActiveSubcategory] = useState<string | null>(null);
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [inStockOnly, setInStockOnly] = useState(false);
  const [brand, setBrand] = useState<string | null>(null);
  const [merchant, setMerchant] = useState<string | null>(null);
  const [brandSearch, setBrandSearch] = useState("");
  const [merchantSearch, setMerchantSearch] = useState("");
  const [sort, setSort] = useState<FilonOfferSort>("relevance");
  const criteria = useMemo(() => ({ query, category, subcategory: activeSubcategory, brand, merchant, sort }), [query, category, activeSubcategory, brand, merchant, sort]);
  const feed = useFilonOfferFeed(criteria, Boolean(query || category));
  const facets = useFilonCatalogueFacets(filtersOpen);
  const merchants = useFilonCatalogueMerchants(filtersOpen);
  const rawRecords = useMemo(() => feed.data?.pages.flatMap((page) => page.items) ?? [], [feed.data]);
  const evidenceNow = useFilonEvidenceNow(rawRecords.map((offer) => offer.observedAt));
  const records = useMemo(() => filterOffers(rawRecords, { inStockOnly, merchant, brand }, evidenceNow), [rawRecords, inStockOnly, merchant, brand, evidenceNow]);
  const total = feed.data?.pages[0]?.total ?? 0;
  const brandSuggestions = useMemo(() => (facets.data?.brands ?? []).filter((item) => !brandSearch.trim() || item.value.toLocaleLowerCase().includes(brandSearch.trim().toLocaleLowerCase())).slice(0, 8), [facets.data, brandSearch]);
  const merchantSuggestions = useMemo(() => (merchants.data ?? []).filter((item) => !merchantSearch.trim() || item.name.toLocaleLowerCase().includes(merchantSearch.trim().toLocaleLowerCase())).slice(0, 8), [merchants.data, merchantSearch]);
  const openOffer = (offer: FilonOffer) => router.push({ pathname: "/product/[id]", params: { id: String(offer.id), name: offer.name, price: String(offer.price), currency: offer.currency, merchant: offer.merchantName, image: offer.imageUrl ?? "", link: offer.link, stock: offer.inStock === true ? "1" : offer.inStock === false ? "0" : "unknown", observedAt: offer.observedAt ?? "", evidenceCurrent: offer.evidenceCurrent === true ? "1" : "0", category: offer.category ?? "" } } as never);
  const resetFilters = () => { setInStockOnly(false); setBrand(null); setMerchant(null); setBrandSearch(""); setMerchantSearch(""); setSort("relevance"); };
  const more = () => { if (feed.hasNextPage && !feed.isFetchingNextPage) void feed.fetchNextPage(); };

  return <View style={styles.resultsRoot}>
    <View style={styles.resultsTop}><View><Text style={styles.resultTitle}>{title}</Text><Text style={styles.resultMeta}>{records.length} / {total} {text.results}</Text></View><Pressable accessibilityRole="button" accessibilityLabel={text.filter} onPress={() => setFiltersOpen(true)} style={({ pressed }) => [styles.filterButton, pressed && styles.pressed]}><MaterialIcons name="tune" size={20} color={colors.primary} /></Pressable></View>
    {subcategories && subcategories.length > 0 ? <View style={styles.chipWrap}><Chip styles={styles} label={text.all} active={!activeSubcategory} onPress={() => setActiveSubcategory(null)} />{subcategories.map((sub) => { const option = localizedTaxonomyOption(sub, locale); return <Chip styles={styles} key={sub.slug ?? option.canonicalName} label={`${option.label} · ${sub.count.toLocaleString(locale === "en" ? "en-BE" : `${locale}-BE`)}`} active={activeSubcategory === option.canonicalName} onPress={() => setActiveSubcategory(option.canonicalName)} />; })}</View> : null}
    <FlatList data={records} keyExtractor={(item) => String(item.id)} renderItem={({ item }) => <NativeOfferRow styles={styles} colors={colors} offer={item} evidenceNow={evidenceNow} onPress={() => openOffer(item)} />} ItemSeparatorComponent={() => <View style={styles.separator} />} onEndReached={more} onEndReachedThreshold={0.65} contentContainerStyle={styles.offerList} ListEmptyComponent={feed.isLoading ? <ActivityIndicator color={colors.primary} style={styles.loader} /> : feed.isError ? <View style={styles.state}><Text style={styles.stateText}>{text.error}</Text><TactileButton accessibilityLabel={text.retry} onPress={() => void feed.refetch()} style={styles.retry}><Text style={styles.retryText}>{text.retry}</Text></TactileButton></View> : <View style={styles.state}><Text style={styles.stateText}>{text.empty}</Text></View>} ListFooterComponent={feed.hasNextPage ? <TactileButton accessibilityLabel={text.loadMore} onPress={more} disabled={feed.isFetchingNextPage} style={styles.more}>{feed.isFetchingNextPage ? <ActivityIndicator color={colors.background} /> : <Text style={styles.moreText}>{text.loadMore}</Text>}</TactileButton> : null} />
    <FilterSheet visible={filtersOpen} styles={styles} colors={colors} text={text} inStockOnly={inStockOnly} sort={sort} brand={brand} merchant={merchant} brandSearch={brandSearch} merchantSearch={merchantSearch} brandSuggestions={brandSuggestions} merchantSuggestions={merchantSuggestions} loadingFacets={facets.isLoading || merchants.isLoading} onClose={() => setFiltersOpen(false)} onReset={resetFilters} onApply={() => setFiltersOpen(false)} onStockChange={setInStockOnly} onSortChange={setSort} onBrandSearchChange={setBrandSearch} onMerchantSearchChange={setMerchantSearch} onBrandChange={setBrand} onMerchantChange={setMerchant} />
  </View>;
}

function FilterSheet({ visible, styles, colors, text, inStockOnly, sort, brand, merchant, brandSearch, merchantSearch, brandSuggestions, merchantSuggestions, loadingFacets, onClose, onReset, onApply, onStockChange, onSortChange, onBrandSearchChange, onMerchantSearchChange, onBrandChange, onMerchantChange }: { visible: boolean; styles: CatalogueStyles; colors: ReturnType<typeof useColors>; text: (typeof copy)[keyof typeof copy]; inStockOnly: boolean; sort: FilonOfferSort; brand: string | null; merchant: string | null; brandSearch: string; merchantSearch: string; brandSuggestions: { value: string; count: number }[]; merchantSuggestions: { name: string; slug: string }[]; loadingFacets: boolean; onClose: () => void; onReset: () => void; onApply: () => void; onStockChange: (value: boolean) => void; onSortChange: (value: FilonOfferSort) => void; onBrandSearchChange: (value: string) => void; onMerchantSearchChange: (value: string) => void; onBrandChange: (value: string | null) => void; onMerchantChange: (value: string | null) => void }) {
  const sortOptions: { value: FilonOfferSort; label: string }[] = [{ value: "relevance", label: text.relevance }, { value: "name", label: text.name }];
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.scrim}><Pressable accessibilityRole="button" accessibilityLabel={text.closeFilters} style={StyleSheet.absoluteFill} onPress={onClose} /><View accessibilityViewIsModal style={styles.sheet}><View style={styles.grabber} /><View style={styles.sheetHeading}><Text style={styles.sheetTitle}>{text.filter}</Text><Pressable accessibilityRole="button" accessibilityLabel={text.clear} onPress={onReset}><Text style={styles.reset}>{text.clear}</Text></Pressable></View><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.sheetContent}><View style={styles.switchRow}><Text style={styles.switchLabel}>{text.stock}</Text><Switch accessibilityLabel={text.stock} value={inStockOnly} onValueChange={onStockChange} trackColor={{ false: colors.border, true: colors.primary }} thumbColor={colors.foreground} /></View><Text style={styles.fieldLabel}>{text.sort}</Text><View style={styles.choiceWrap}>{sortOptions.map((option) => <Chip key={option.value} styles={styles} label={option.label} active={sort === option.value} onPress={() => onSortChange(option.value)} />)}</View><FilterSuggestions styles={styles} colors={colors} label={text.brand} placeholder={text.searchBrand} value={brandSearch} selected={brand} suggestions={brandSuggestions.map((item) => ({ id: item.value, label: item.value }))} loading={loadingFacets} onChangeText={onBrandSearchChange} onSelect={(value) => { onBrandChange(brand === value ? null : value); onBrandSearchChange(value); }} /><FilterSuggestions styles={styles} colors={colors} label={text.merchant} placeholder={text.searchMerchant} value={merchantSearch} selected={merchant} suggestions={merchantSuggestions.map((item) => ({ id: item.slug, label: item.name }))} loading={loadingFacets} onChangeText={onMerchantSearchChange} onSelect={(value) => { onMerchantChange(merchant === value ? null : value); onMerchantSearchChange(merchantSuggestions.find((item) => item.slug === value)?.name ?? ""); }} /><TactileButton accessibilityLabel={text.apply} onPress={onApply} style={styles.sheetApply}><Text style={styles.sheetApplyText}>{text.apply}</Text></TactileButton></ScrollView></View></View></Modal>;
}

function FilterSuggestions({ styles, colors, label, placeholder, value, selected, suggestions, loading, onChangeText, onSelect }: { styles: CatalogueStyles; colors: ReturnType<typeof useColors>; label: string; placeholder: string; value: string; selected: string | null; suggestions: { id: string; label: string }[]; loading: boolean; onChangeText: (value: string) => void; onSelect: (value: string) => void }) { return <View style={styles.suggestionSection}><Text style={styles.fieldLabel}>{label}</Text><View style={styles.searchField}><MaterialIcons name="search" size={17} color={colors.muted} /><TextInput accessibilityLabel={label} value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={colors.muted} style={styles.searchInput} /></View>{loading ? <ActivityIndicator color={colors.primary} style={styles.suggestionsLoader} /> : <View style={styles.choiceWrap}>{suggestions.map((item) => <Chip key={item.id} styles={styles} label={item.label} active={selected === item.id || selected === item.label} onPress={() => onSelect(item.id)} />)}</View>}</View>; }

function NativeOfferRow({ offer, evidenceNow, onPress, styles, colors }: { offer: FilonOffer; evidenceNow: number; onPress: () => void; styles: CatalogueStyles; colors: ReturnType<typeof useColors> }) {
  const { locale } = useLocale();
  const text = copy[locale];
  const currentStock = currentFilonStock(offer, evidenceNow);
  const availability = currentStock === true ? text.available : currentStock === false ? text.unavailable : text.unknown;
  const price = formatFilonPrice(offer.price, locale, offer.currency);
  const priceCurrent = isFilonOfferPriceCurrent(offer, evidenceNow);
  const qualifiedPrice = priceCurrent ? price : text.priceUnknown;
  return <Pressable accessibilityRole="button" accessibilityLabel={`${offer.name}, ${qualifiedPrice}, ${availability}`} onPress={onPress} style={({ pressed }) => [styles.offerRow, pressed && styles.pressed]}>{offer.imageUrl ? <Image source={{ uri: offer.imageUrl }} style={styles.thumbnail} contentFit="contain" transition={150} /> : <View style={styles.thumbnailFallback}><MaterialIcons name="image-not-supported" size={18} color={colors.primary} /></View>}<View style={styles.offerBody}><Text numberOfLines={2} style={styles.offerName}>{offer.name}</Text><Text numberOfLines={1} style={styles.offerMerchant}>{text.at} {offer.merchantName}</Text><View style={styles.offerFooter}><Text numberOfLines={1} style={[styles.offerPrice, !priceCurrent && styles.offerPriceStale]}>{qualifiedPrice}</Text><Text style={[styles.offerAvailability, currentStock === false ? styles.offerUnavailable : currentStock === null ? styles.offerUnknown : null]}>{availability}</Text></View></View><MaterialIcons name="chevron-right" size={21} color={colors.muted} /></Pressable>;
}

function Chip({ label, active, onPress, styles }: { label: string; active: boolean; onPress: () => void; styles: CatalogueStyles }) { return <Pressable accessibilityRole="button" accessibilityState={{ selected: active }} onPress={onPress} style={({ pressed }) => [styles.chip, active && styles.chipActive, pressed && styles.pressed]}><Text numberOfLines={1} style={[styles.chipText, active && styles.chipTextActive]}>{label}</Text></Pressable>; }

function createStyles(colors: ReturnType<typeof useColors>) { return StyleSheet.create({
  header: { minHeight: 64, flexDirection: "row", alignItems: "center", gap: 12, paddingHorizontal: 20, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border, backgroundColor: colors.background }, back: { width: 42, height: 42, marginLeft: -7, alignItems: "center", justifyContent: "center", borderRadius: 14, backgroundColor: colors.surface }, logoMark: { width: 32, height: 32, alignItems: "center", justifyContent: "center", borderRadius: 10, backgroundColor: colors.primary }, logoText: { color: colors.background, fontSize: 17, fontWeight: "900" }, headerWords: { flex: 1, minWidth: 0 }, headerTitle: { color: colors.foreground, fontSize: 17, lineHeight: 22, fontWeight: "800" }, headerSubtitle: { color: colors.muted, fontSize: 11, lineHeight: 15, fontWeight: "700", marginTop: 1 }, rightSpacer: { width: 32 }, resultsRoot: { flex: 1 },
  resultsTop: { minHeight: 72, paddingHorizontal: 20, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, resultTitle: { color: colors.foreground, fontSize: 24, fontWeight: "800", letterSpacing: -0.5 }, resultMeta: { color: colors.muted, fontSize: 11, fontWeight: "700", marginTop: 4 }, filterButton: { width: 44, height: 44, borderRadius: 15, justifyContent: "center", alignItems: "center", backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border },
  chipWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8, paddingHorizontal: 20, paddingBottom: 14 }, chip: { maxWidth: "100%", minHeight: 38, justifyContent: "center", paddingHorizontal: 12, borderRadius: 14, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, chipActive: { borderColor: colors.primary, backgroundColor: colors.primary }, chipText: { color: colors.foreground, fontSize: 11, fontWeight: "700" }, chipTextActive: { color: colors.background },
  offerList: { paddingHorizontal: 20, paddingBottom: 118 }, offerRow: { minHeight: 96, padding: 10, flexDirection: "row", alignItems: "center", gap: 12, borderRadius: 20, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, thumbnail: { width: 74, height: 74, borderRadius: 14, backgroundColor: colors.background }, thumbnailFallback: { width: 74, height: 74, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: `${colors.primary}12`, borderWidth: 1, borderColor: `${colors.primary}35` }, offerBody: { flex: 1, minWidth: 0, alignSelf: "stretch", justifyContent: "center" }, offerName: { color: colors.foreground, fontSize: 14, lineHeight: 19, fontWeight: "800" }, offerMerchant: { color: colors.muted, fontSize: 11, lineHeight: 15, fontWeight: "700", marginTop: 4 }, offerFooter: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8, marginTop: 4 }, offerPrice: { flexShrink: 1, color: colors.primary, fontSize: 15, lineHeight: 19, fontWeight: "900" }, offerPriceStale: { color: colors.warning, fontSize: 11 }, offerAvailability: { color: colors.success, fontSize: 10, fontWeight: "800" }, offerUnavailable: { color: colors.error }, offerUnknown: { color: colors.warning }, separator: { height: 10 },
  loader: { marginTop: 42 }, state: { minHeight: 160, alignItems: "center", justifyContent: "center", gap: 13, padding: 24 }, stateText: { color: colors.muted, textAlign: "center", fontSize: 13, lineHeight: 19 }, retry: { minHeight: 44, paddingHorizontal: 16, borderRadius: 14, backgroundColor: colors.primary }, retryText: { color: colors.background, fontWeight: "800", fontSize: 12 }, more: { minHeight: 50, marginTop: 18, borderRadius: 16, backgroundColor: colors.primary }, moreText: { color: colors.background, fontSize: 13, fontWeight: "800" },
  scrim: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(0,0,0,0.48)" }, sheet: { maxHeight: "88%", paddingTop: 14, borderTopLeftRadius: 30, borderTopRightRadius: 30, backgroundColor: colors.surface, borderTopWidth: 1, borderColor: colors.border }, grabber: { width: 38, height: 4, alignSelf: "center", borderRadius: 3, backgroundColor: colors.muted, marginBottom: 12 }, sheetHeading: { paddingHorizontal: 20, flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, sheetTitle: { color: colors.foreground, fontSize: 20, fontWeight: "800" }, reset: { color: colors.primary, fontSize: 12, fontWeight: "800" }, sheetContent: { padding: 20, paddingTop: 14, paddingBottom: 32 }, priceRow: { flexDirection: "row", gap: 10 }, priceColumn: { flex: 1 }, fieldLabel: { color: colors.muted, fontSize: 12, fontWeight: "700", marginTop: 15, marginBottom: 7 }, priceField: { minHeight: 52, paddingHorizontal: 12, borderRadius: 15, flexDirection: "row", alignItems: "center", backgroundColor: colors.background, borderWidth: 1, borderColor: colors.border }, priceInput: { flex: 1, minHeight: 50, color: colors.foreground, fontSize: 16, fontWeight: "700" }, eur: { color: colors.primary, fontSize: 11, fontWeight: "800" }, switchRow: { minHeight: 62, flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 12 }, switchLabel: { color: colors.foreground, fontSize: 14, fontWeight: "700" }, choiceWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, suggestionSection: { marginTop: 5 }, searchField: { minHeight: 48, paddingHorizontal: 12, borderRadius: 15, flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: colors.background, borderWidth: 1, borderColor: colors.border }, searchInput: { flex: 1, minHeight: 46, color: colors.foreground, fontSize: 14, fontWeight: "600" }, suggestionsLoader: { marginTop: 14 }, sheetApply: { minHeight: 54, marginTop: 22, borderRadius: 17, backgroundColor: colors.primary }, sheetApplyText: { color: colors.background, fontWeight: "800", fontSize: 14 }, pressed: { opacity: 0.78, transform: [{ scale: 0.985 }] },
}); }
