import type { Locale } from "@/lib/i18n";

/**
 * Les flux partenaires conservent les noms de rayons en français. Cette couche
 * traduit l’interface de navigation sans altérer les slugs, les données SEO ou
 * les intitulés marchands.
 */
const LABELS: Record<string, Partial<Record<Locale, string>>> = {
  "Mode & Accessoires": { nl: "Mode & accessoires", en: "Fashion & accessories" },
  "Mode femme": { nl: "Damesmode", en: "Women's fashion" },
  "Mode homme": { nl: "Herenmode", en: "Men's fashion" },
  "Mode enfant": { nl: "Kindermode", en: "Children's fashion" },
  "Chaussures": { nl: "Schoenen", en: "Footwear" },
  "Accessoires": { nl: "Accessoires", en: "Accessories" },
  "Bagagerie": { nl: "Tassen & bagage", en: "Bags & luggage" },
  "Bijoux & Montres": { nl: "Sieraden & horloges", en: "Jewellery & watches" },
  "High-Tech": { nl: "High-tech", en: "Tech" },
  "Informatique": { nl: "Computers", en: "Computing" },
  "Téléphonie": { nl: "Telefonie", en: "Phones" },
  "TV & Son": { nl: "TV & audio", en: "TV & audio" },
  "Photo": { nl: "Fotografie", en: "Photography" },
  "Gaming": { nl: "Gaming", en: "Gaming" },
  "Maison & Déco": { nl: "Huis & decor", en: "Home & decor" },
  "Beauté & Parfum": { nl: "Beauty & parfum", en: "Beauty & fragrance" },
  "Auto & Moto": { nl: "Auto & motor", en: "Cars & motorbikes" },
  "Sport & Plein air": { nl: "Sport & outdoor", en: "Sports & outdoor" },
  "Animalerie": { nl: "Dieren", en: "Pets" },
  "Bébé & Santé": { nl: "Baby & gezondheid", en: "Baby & health" },
  "Famille & Quotidien": { nl: "Familie & dagelijks leven", en: "Family & everyday" },
  "Voyage & Loisirs": { nl: "Reizen & vrije tijd", en: "Travel & leisure" },
  "Jardin & Bricolage": { nl: "Tuin & klussen", en: "Garden & DIY" },
  "Électroménager": { nl: "Huishoudtoestellen", en: "Home appliances" },
  "Alimentation": { nl: "Voeding", en: "Food & drink" },
  "Alimentation & Boissons": { nl: "Eten & drinken", en: "Food & drink" },
  "Bébé & Puériculture": { nl: "Baby & verzorging", en: "Baby & nursery" },
  "Bébé (0-2 ans)": { nl: "Baby (0-2 jaar)", en: "Baby (0-2 years)" },
  "Beauté & Santé": { nl: "Beauty & gezondheid", en: "Beauty & health" },
  "Livres & Culture": { nl: "Boeken & cultuur", en: "Books & culture" },
  "Loisirs créatifs": { nl: "Creatieve hobby's", en: "Creative hobbies" },
  "Sport & Loisirs": { nl: "Sport & vrije tijd", en: "Sports & leisure" },
  "Mode": { nl: "Mode", en: "Fashion" },
  "Robes": { nl: "Jurken", en: "Dresses" },
  "Jupes": { nl: "Rokken", en: "Skirts" },
  "Hauts & T-shirts": { nl: "Tops & T-shirts", en: "Tops & T-shirts" },
  "Pulls & Sweats": { nl: "Truien & sweaters", en: "Jumpers & sweatshirts" },
  "Pantalons & Jeans": { nl: "Broeken & jeans", en: "Trousers & jeans" },
  "Manteaux & Vestes": { nl: "Jassen", en: "Coats & jackets" },
  "Lingerie & Nuit": { nl: "Lingerie & nachtmode", en: "Lingerie & nightwear" },
  "Maillots de bain": { nl: "Badmode", en: "Swimwear" },
  "Chemises": { nl: "Overhemden", en: "Shirts" },
  "T-shirts & Polos": { nl: "T-shirts & polo's", en: "T-shirts & polos" },
  "Sous-vêtements": { nl: "Ondergoed", en: "Underwear" },
  "Chaussettes": { nl: "Sokken", en: "Socks" },
  "Costumes": { nl: "Pakken", en: "Suits" },
  "Fille": { nl: "Meisjes", en: "Girls" },
  "Garçon": { nl: "Jongens", en: "Boys" },
  "Baskets & Sneakers": { nl: "Sneakers", en: "Sneakers" },
  "Bottes & Bottines": { nl: "Laarzen & enkellaarsjes", en: "Boots & ankle boots" },
  "Escarpins & Talons": { nl: "Pumps & hakken", en: "Heels & pumps" },
  "Sandales": { nl: "Sandalen", en: "Sandals" },
  "Mocassins & Ville": { nl: "Mocassins & nette schoenen", en: "Loafers & formal shoes" },
  "Chaussons": { nl: "Pantoffels", en: "Slippers" },
  "Semelles & Entretien": { nl: "Inlegzolen & onderhoud", en: "Insoles & care" },
  "Lunettes de soleil": { nl: "Zonnebrillen", en: "Sunglasses" },
  "Ceintures": { nl: "Riemen", en: "Belts" },
  "Chapeaux & Casquettes": { nl: "Hoeden & petten", en: "Hats & caps" },
  "Écharpes & Foulards": { nl: "Sjaals", en: "Scarves" },
  "Gants": { nl: "Handschoenen", en: "Gloves" },
  "Sacs à main": { nl: "Handtassen", en: "Handbags" },
  "Sacs à dos": { nl: "Rugzakken", en: "Backpacks" },
  "Valises & Bagages": { nl: "Koffers & bagage", en: "Suitcases & luggage" },
  "Portefeuilles": { nl: "Portemonnees", en: "Wallets" },
  "Sacs banane & Pochettes": { nl: "Heuptassen & clutches", en: "Bum bags & clutches" },
  "Colliers & Pendentifs": { nl: "Kettingen & hangers", en: "Necklaces & pendants" },
  "Bracelets": { nl: "Armbanden", en: "Bracelets" },
  "Bagues": { nl: "Ringen", en: "Rings" },
  "Boucles d'oreilles": { nl: "Oorbellen", en: "Earrings" },
  "Montres": { nl: "Horloges", en: "Watches" },
  "Ordinateurs portables": { nl: "Laptops", en: "Laptops" },
  "Écrans": { nl: "Schermen", en: "Monitors" },
  "Claviers & Souris": { nl: "Toetsenborden & muizen", en: "Keyboards & mice" },
  "Stockage": { nl: "Opslag", en: "Storage" },
  "Imprimantes": { nl: "Printers", en: "Printers" },
  "Réseau": { nl: "Netwerk", en: "Networking" },
  "Câbles & Adaptateurs": { nl: "Kabels & adapters", en: "Cables & adapters" },
  "Smartphones": { nl: "Smartphones", en: "Smartphones" },
  "Coques & Protections": { nl: "Hoesjes & bescherming", en: "Cases & protection" },
  "Chargeurs & Batteries": { nl: "Opladers & batterijen", en: "Chargers & batteries" },
  "Écouteurs": { nl: "Oordopjes", en: "Earbuds" },
  "Montres connectées": { nl: "Smartwatches", en: "Smartwatches" },
  "Téléviseurs": { nl: "Televisies", en: "Televisions" },
  "Casques audio": { nl: "Koptelefoons", en: "Headphones" },
  "Enceintes": { nl: "Speakers", en: "Speakers" },
  "Barres de son": { nl: "Soundbars", en: "Soundbars" },
  "Platines & Hi-Fi": { nl: "Platenspelers & hi-fi", en: "Turntables & hi-fi" },
  "Jeux vidéo": { nl: "Videogames", en: "Video games" },
  "Consoles": { nl: "Consoles", en: "Consoles" },
  "Accessoires gaming": { nl: "Gamingaccessoires", en: "Gaming accessories" },
  "Aspirateurs": { nl: "Stofzuigers", en: "Vacuum cleaners" },
  "Gros électroménager": { nl: "Grote huishoudtoestellen", en: "Large appliances" },
  "Petit électroménager": { nl: "Kleine huishoudtoestellen", en: "Small appliances" },
  "Jardinage": { nl: "Tuinieren", en: "Gardening" },
  "Mobilier de jardin": { nl: "Tuinmeubelen", en: "Garden furniture" },
  "Outillage": { nl: "Gereedschap", en: "Tools" },
  "Décoration": { nl: "Decoratie", en: "Decoration" },
  "Meubles": { nl: "Meubels", en: "Furniture" },
};

export function catalogueLabel(name: string, locale: Locale): string {
  return locale === "fr" ? name : LABELS[name]?.[locale] ?? name;
}
