"""Baseline du schéma FILON Core et Intelligence.

Revision ID: b9db07b15986
Revises:
Create Date: 2026-08-28 20:05:13.646408
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'b9db07b15986'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ean', sa.String(length=14), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('brand', sa.String(length=191), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('offers_count', sa.Integer(), nullable=False),
    sa.Column('merchants_count', sa.Integer(), nullable=False),
    sa.Column('price_min', sa.Float(), nullable=True),
    sa.Column('price_max', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalog_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_products_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_products_ean'), ['ean'], unique=True)
        batch_op.create_index(batch_op.f('ix_catalog_products_merchants_count'), ['merchants_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_products_price_min'), ['price_min'], unique=False)

    op.create_table('catalog_sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('merchants_count', sa.Integer(), nullable=False),
    sa.Column('feeds_count', sa.Integer(), nullable=False),
    sa.Column('offers_count', sa.Integer(), nullable=False),
    sa.Column('skipped_feeds', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalog_sync_runs', schema=None) as batch_op:
        batch_op.create_index('ix_catalog_sync_runs_started', ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_sync_runs_status'), ['status'], unique=False)
        batch_op.create_index('uq_catalog_sync_runs_running', ['status'], unique=True, postgresql_where=sa.text("status = 'running'"), sqlite_where=sa.text("status = 'running'"))

    op.create_table('intelligence_benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=48), nullable=False),
    sa.Column('case_key', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('expected_json', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain', 'case_key', 'version', name='uq_intelligence_benchmark_version')
    )
    with op.batch_alter_table('intelligence_benchmarks', schema=None) as batch_op:
        batch_op.create_index('ix_intelligence_benchmark_domain_status', ['domain', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_benchmarks_case_key'), ['case_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_benchmarks_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_benchmarks_status'), ['status'], unique=False)

    op.create_table('intelligence_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_key', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('request_json', sa.JSON(), nullable=True),
    sa.Column('intent_json', sa.JSON(), nullable=True),
    sa.Column('candidates_json', sa.JSON(), nullable=True),
    sa.Column('filters_json', sa.JSON(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('rules_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trace_key', name='uq_intelligence_trace_key')
    )
    with op.batch_alter_table('intelligence_traces', schema=None) as batch_op:
        batch_op.create_index('ix_intelligence_trace_domain_status', ['domain', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_traces_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_traces_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_traces_trace_key'), ['trace_key'], unique=True)

    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('awin_mid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=8), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('cashback', sa.String(length=64), nullable=True),
    sa.Column('joined', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_merchants_awin_mid'), ['awin_mid'], unique=True)
        batch_op.create_index(batch_op.f('ix_merchants_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_merchants_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_merchants_slug'), ['slug'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_external_id'), ['external_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_external_id', sa.String(length=128), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intelligence_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_key', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['intelligence_traces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intelligence_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intelligence_feedback_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_feedback_recommendation_key'), ['recommendation_key'], unique=False)
        batch_op.create_index('ix_intelligence_feedback_trace_action', ['trace_id', 'action'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_feedback_trace_id'), ['trace_id'], unique=False)

    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('awin_product_id', sa.String(length=191), nullable=False),
    sa.Column('ean', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('brand', sa.String(length=191), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('filon_category', sa.String(length=64), nullable=True),
    sa.Column('filon_subcategory', sa.String(length=64), nullable=True),
    sa.Column('offer_kind', sa.String(length=32), nullable=True),
    sa.Column('dedup_key', sa.String(length=191), nullable=True),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.Column('is_adult', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('deep_link', sa.Text(), nullable=True),
    sa.Column('product_url', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'awin_product_id', name='uq_offer_merchant_product')
    )
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index('ix_offer_brand', ['brand'], unique=False)
        batch_op.create_index('ix_offer_category', ['category'], unique=False)
        batch_op.create_index('ix_offer_ean', ['ean'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_dedup_key'), ['dedup_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_filon_category'), ['filon_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_filon_subcategory'), ['filon_subcategory'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_is_adult'), ['is_adult'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_is_canonical'), ['is_canonical'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_offer_kind'), ['offer_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_product_id'), ['product_id'], unique=False)

    # Ces index accélèrent la recherche par sous-chaîne sur le catalogue
    # PostgreSQL. Ils n'ont pas d'équivalent SQLite et sont donc exclus des
    # tests de migration éphémères.
    if op.get_bind().dialect.name == 'postgresql':
        op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
        op.create_index(
            'ix_offers_name_trgm',
            'offers',
            ['name'],
            postgresql_using='gin',
            postgresql_ops={'name': 'gin_trgm_ops'},
        )
        op.create_index(
            'ix_offers_brand_trgm',
            'offers',
            ['brand'],
            postgresql_using='gin',
            postgresql_ops={'brand': 'gin_trgm_ops'},
        )

    op.create_table('search_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intelligence_product_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('catalog_product_id', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_type', sa.String(length=48), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extractor_version', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_product_id'], ['catalog_products.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offer_id', 'catalog_product_id', 'field', 'extractor_version', name='uq_intelligence_fact_target_field_version')
    )
    with op.batch_alter_table('intelligence_product_facts', schema=None) as batch_op:
        batch_op.create_index('ix_intelligence_fact_offer_field', ['offer_id', 'field'], unique=False)
        batch_op.create_index('ix_intelligence_fact_product_field', ['catalog_product_id', 'field'], unique=False)
        batch_op.create_index('ix_intelligence_fact_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_product_facts_catalog_product_id'), ['catalog_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_product_facts_field'), ['field'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_product_facts_offer_id'), ['offer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_product_facts_status'), ['status'], unique=False)

    op.create_table('intelligence_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_offer_id', sa.Integer(), nullable=True),
    sa.Column('target_offer_id', sa.Integer(), nullable=True),
    sa.Column('source_catalog_product_id', sa.Integer(), nullable=True),
    sa.Column('target_catalog_product_id', sa.Integer(), nullable=True),
    sa.Column('relation_type', sa.String(length=48), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=48), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_catalog_product_id'], ['catalog_products.id'], ),
    sa.ForeignKeyConstraint(['source_offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['target_catalog_product_id'], ['catalog_products.id'], ),
    sa.ForeignKeyConstraint(['target_offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_offer_id', 'target_offer_id', 'relation_type', 'version', name='uq_intelligence_relation_offer_version')
    )
    with op.batch_alter_table('intelligence_relations', schema=None) as batch_op:
        batch_op.create_index('ix_intelligence_relation_source_type', ['source_offer_id', 'relation_type'], unique=False)
        batch_op.create_index('ix_intelligence_relation_target_type', ['target_offer_id', 'relation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_relations_relation_type'), ['relation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_relations_source_catalog_product_id'), ['source_catalog_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_relations_source_offer_id'), ['source_offer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_relations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_relations_target_catalog_product_id'), ['target_catalog_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_relations_target_offer_id'), ['target_offer_id'], unique=False)

    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_snapshots_offer_id'), ['offer_id'], unique=False)
        batch_op.create_index('ix_snapshot_offer_time', ['offer_id', 'captured_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshot_offer_time')
        batch_op.drop_index(batch_op.f('ix_price_snapshots_offer_id'))

    op.drop_table('price_snapshots')
    with op.batch_alter_table('intelligence_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intelligence_relations_target_offer_id'))
        batch_op.drop_index(batch_op.f('ix_intelligence_relations_target_catalog_product_id'))
        batch_op.drop_index(batch_op.f('ix_intelligence_relations_status'))
        batch_op.drop_index(batch_op.f('ix_intelligence_relations_source_offer_id'))
        batch_op.drop_index(batch_op.f('ix_intelligence_relations_source_catalog_product_id'))
        batch_op.drop_index(batch_op.f('ix_intelligence_relations_relation_type'))
        batch_op.drop_index('ix_intelligence_relation_target_type')
        batch_op.drop_index('ix_intelligence_relation_source_type')

    op.drop_table('intelligence_relations')
    with op.batch_alter_table('intelligence_product_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intelligence_product_facts_status'))
        batch_op.drop_index(batch_op.f('ix_intelligence_product_facts_offer_id'))
        batch_op.drop_index(batch_op.f('ix_intelligence_product_facts_field'))
        batch_op.drop_index(batch_op.f('ix_intelligence_product_facts_catalog_product_id'))
        batch_op.drop_index('ix_intelligence_fact_status')
        batch_op.drop_index('ix_intelligence_fact_product_field')
        batch_op.drop_index('ix_intelligence_fact_offer_field')

    op.drop_table('intelligence_product_facts')
    op.drop_table('search_logs')
    if op.get_bind().dialect.name == 'postgresql':
        op.drop_index('ix_offers_brand_trgm', table_name='offers')
        op.drop_index('ix_offers_name_trgm', table_name='offers')

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offers_product_id'))
        batch_op.drop_index(batch_op.f('ix_offers_offer_kind'))
        batch_op.drop_index(batch_op.f('ix_offers_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_offers_is_canonical'))
        batch_op.drop_index(batch_op.f('ix_offers_is_adult'))
        batch_op.drop_index(batch_op.f('ix_offers_filon_subcategory'))
        batch_op.drop_index(batch_op.f('ix_offers_filon_category'))
        batch_op.drop_index(batch_op.f('ix_offers_dedup_key'))
        batch_op.drop_index('ix_offer_ean')
        batch_op.drop_index('ix_offer_category')
        batch_op.drop_index('ix_offer_brand')

    op.drop_table('offers')
    with op.batch_alter_table('intelligence_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intelligence_feedback_trace_id'))
        batch_op.drop_index('ix_intelligence_feedback_trace_action')
        batch_op.drop_index(batch_op.f('ix_intelligence_feedback_recommendation_key'))
        batch_op.drop_index(batch_op.f('ix_intelligence_feedback_action'))

    op.drop_table('intelligence_feedback')
    op.drop_table('alerts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_external_id'))

    op.drop_table('products')
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merchants_slug'))
        batch_op.drop_index(batch_op.f('ix_merchants_region'))
        batch_op.drop_index(batch_op.f('ix_merchants_domain'))
        batch_op.drop_index(batch_op.f('ix_merchants_awin_mid'))

    op.drop_table('merchants')
    with op.batch_alter_table('intelligence_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intelligence_traces_trace_key'))
        batch_op.drop_index(batch_op.f('ix_intelligence_traces_status'))
        batch_op.drop_index(batch_op.f('ix_intelligence_traces_domain'))
        batch_op.drop_index('ix_intelligence_trace_domain_status')

    op.drop_table('intelligence_traces')
    with op.batch_alter_table('intelligence_benchmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intelligence_benchmarks_status'))
        batch_op.drop_index(batch_op.f('ix_intelligence_benchmarks_domain'))
        batch_op.drop_index(batch_op.f('ix_intelligence_benchmarks_case_key'))
        batch_op.drop_index('ix_intelligence_benchmark_domain_status')

    op.drop_table('intelligence_benchmarks')
    with op.batch_alter_table('catalog_sync_runs', schema=None) as batch_op:
        batch_op.drop_index('uq_catalog_sync_runs_running', postgresql_where=sa.text("status = 'running'"), sqlite_where=sa.text("status = 'running'"))
        batch_op.drop_index(batch_op.f('ix_catalog_sync_runs_status'))
        batch_op.drop_index('ix_catalog_sync_runs_started')

    op.drop_table('catalog_sync_runs')
    with op.batch_alter_table('catalog_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_products_price_min'))
        batch_op.drop_index(batch_op.f('ix_catalog_products_merchants_count'))
        batch_op.drop_index(batch_op.f('ix_catalog_products_ean'))
        batch_op.drop_index(batch_op.f('ix_catalog_products_brand'))

    op.drop_table('catalog_products')
    # ### end Alembic commands ###
