"""raw observation quarantine shadow

Revision ID: d75faf1f6a94
Revises: b9db07b15986
Create Date: 2026-08-28 20:37:55.777499
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'd75faf1f6a94'
down_revision: Union[str, None] = 'b9db07b15986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_source_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=48), nullable=False),
    sa.Column('source_ref', sa.String(length=191), nullable=False),
    sa.Column('source_record_key', sa.String(length=255), nullable=False),
    sa.Column('schema_version', sa.String(length=64), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('payload_checksum', sa.String(length=64), nullable=False),
    sa.Column('replay_key', sa.String(length=64), nullable=False),
    sa.Column('sync_run_id', sa.Integer(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('length(payload_checksum) = 64', name='ck_raw_source_checksum_sha256'),
    sa.CheckConstraint('length(replay_key) = 64', name='ck_raw_source_replay_key_sha256'),
    sa.ForeignKeyConstraint(['sync_run_id'], ['catalog_sync_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('replay_key', name='uq_raw_source_replay_key')
    )
    with op.batch_alter_table('raw_source_records', schema=None) as batch_op:
        batch_op.create_index('ix_raw_source_lookup', ['source_type', 'source_ref', 'source_record_key'], unique=False)
        batch_op.create_index('ix_raw_source_observed_at', ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_source_records_payload_checksum'), ['payload_checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_source_records_sync_run_id'), ['sync_run_id'], unique=False)

    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_source_record_id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=48), nullable=False),
    sa.Column('subject_ref', sa.String(length=255), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('value_json', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_type', sa.String(length=48), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('transformation', sa.String(length=64), nullable=False),
    sa.Column('transformation_version', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('verified', 'inferred', 'unknown')", name='ck_observation_status'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_observation_confidence'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['raw_source_record_id'], ['raw_source_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_source_record_id', 'subject_type', 'subject_ref', 'field', 'transformation_version', name='uq_observation_projection_field_version')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index('ix_observation_field_status', ['field', 'status'], unique=False)
        batch_op.create_index('ix_observation_observed_at', ['observed_at'], unique=False)
        batch_op.create_index('ix_observation_subject', ['subject_type', 'subject_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_offer_id'), ['offer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_raw_source_record_id'), ['raw_source_record_id'], unique=False)

    op.create_table('quarantine_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_source_record_id', sa.Integer(), nullable=False),
    sa.Column('issue_key', sa.String(length=64), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=True),
    sa.Column('rejected_value_json', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('details_json', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('transformation_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('open', 'released', 'discarded')", name='ck_quarantine_status'),
    sa.ForeignKeyConstraint(['raw_source_record_id'], ['raw_source_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_key', name='uq_quarantine_issue_key')
    )
    with op.batch_alter_table('quarantine_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quarantine_records_raw_source_record_id'), ['raw_source_record_id'], unique=False)
        batch_op.create_index('ix_quarantine_stage', ['stage'], unique=False)
        batch_op.create_index('ix_quarantine_status_error', ['status', 'error_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quarantine_records', schema=None) as batch_op:
        batch_op.drop_index('ix_quarantine_status_error')
        batch_op.drop_index('ix_quarantine_stage')
        batch_op.drop_index(batch_op.f('ix_quarantine_records_raw_source_record_id'))

    op.drop_table('quarantine_records')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_raw_source_record_id'))
        batch_op.drop_index(batch_op.f('ix_observations_offer_id'))
        batch_op.drop_index('ix_observation_subject')
        batch_op.drop_index('ix_observation_observed_at')
        batch_op.drop_index('ix_observation_field_status')

    op.drop_table('observations')
    with op.batch_alter_table('raw_source_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_source_records_sync_run_id'))
        batch_op.drop_index(batch_op.f('ix_raw_source_records_payload_checksum'))
        batch_op.drop_index('ix_raw_source_observed_at')
        batch_op.drop_index('ix_raw_source_lookup')

    op.drop_table('raw_source_records')
    # ### end Alembic commands ###
